tcp: Fix compiler error due to type confusion
tcp_tso_should_defer() used the min() macro on incompatible types (u64 vs long)

  error: comparison of distinct pointer types
  ('typeof (srtt_in_ns >> 1) *' (aka 'unsigned long long *')
  and 'typeof (1000000L) *' (aka 'long *'))

Fix this up by using min_t to ensure the comparison is performed as
unsigned 64-bit integers

Fixes: 8b7ac7af3a6664d707cb451c1cac5d9444977815
Change-Id: Iccd7ae5bdcc3fd77fea126389761cc30c5558315